# Generated by Django 2.0.5 on 2018-05-27 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_articlelike_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelike',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('article', 'user')},
        ),
    ]
